Frontend.Web.App.Admin/Models/ErrorViewModel.cs
namespace Frontend.Web.App.Admin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Frontend.Web.App.Admin/Controllers/HomeController.cs
using Frontend.Web.App.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Frontend.Web.App.Admin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Frontend.Web.App.Admin/Controllers/PartiesController.cs
using Backend.Services.DB.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Frontend.Web.App.Admin.Controllers
{
    public class PartiesController : Controller
    {
        private IPartiesModel model;

        public PartiesController(IPartiesModel iPartiesModel)
        {
            model = iPartiesModel;
        }

        // GET: PartiesController
        public ActionResult Index()
        {
            return View(model.GetParties());
        }

        // GET: PartiesController/Earring/{id}
        public ActionResult Earring(int id)
        {
            model.PutState(id, "P");

            return RedirectToAction(nameof(Index));
        }

        // GET: PartiesController/Approve/{id}
        public ActionResult Approve(int id)
        {
            model.PutState(id, "A");

            return RedirectToAction(nameof(Index));
        }

        // GET: PartiesController/Decline/{id}
        public ActionResult Decline(int id)
        {
            model.PutState(id, "R");

            return RedirectToAction(nameof(Index));
        }
    }
}

Frontend.Web.App.Admin/Controllers/ServicesController.cs
using Backend.Services.DB.Entities;
using Backend.Services.DB.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Frontend.Web.App.Admin.Controllers
{
    public class ServicesController : Controller
    {
        private IServicesModel model;

        public ServicesController(IServicesModel iServicesModel)
        {
            model = iServicesModel;
        }

        // GET: ServicesController
        public ActionResult Index()
        {
            return View(model.GetServices());
        }

        // GET: ServicesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServicesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Service service = new Service();

                service.IDService = 0;
                service.Active = true;
                service.Type = collection["Type"].ToString();
                service.Name = collection["Name"].ToString();
                service.Description = collection["Description"].ToString();
                service.Price = decimal.Parse(collection["Price"].ToString());

                model.PostService(service);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ServicesController/Details/{id}
        public ActionResult Details(int id)
        {
            return View(model.GetService(id));
        }

        // GET: ServicesController/Edit/{id}
        public ActionResult Edit(int id)
        {
            return View(model.GetService(id));
        }

        // POST: ServicesController/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Service service = new Service();

                service.IDService = int.Parse(collection["IDService"].ToString());
                service.Active = collection["Active"].ToString() != "false";
                service.Type = collection["Type"].ToString();
                service.Name = collection["Name"].ToString();
                service.Description = collection["Description"].ToString();
                service.Price = decimal.Parse(collection["Price"].ToString());

                model.PutService(service);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ServicesController/Delete/{id}
        public ActionResult Delete(int id)
        {
            return View(model.GetService(id));
        }

        // POST: ServicesController/Delete/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                model.DeleteService(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Frontend.Web.App.Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div style="width: 100%; background-color: #000; border-radius: 4px">
    <img src="/img/logo.png" style="max-height: 500px; object-fit: cover;" alt="...">
    </div>

    <div class="d-flex flex-column">
        @*<div>
            <a class="py-3 px-5 btn btn-outline-primary fs-3" asp-controller="Parties" asp-action="Index">Gestionar Eventos</a>
        </div>
        <div class="mt-4">
            <a class="py-3 px-5 btn btn-outline-primary fs-3" asp-controller="Services" asp-action="Index">Gestionar Servicios</a>
        </div>*@

        <div class="mt-2 row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card h-100">
                    <img src="/img/eventos.jpg" class="card-img-top" style="max-height: 300px; object-fit: cover;" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><a class="mt-2 py-2 px-4 btn btn-outline-primary fs-4" asp-controller="Parties" asp-action="Index">Gestionar Eventos</a></h5>
                        <p class="mt-4 card-text">Gestionar cada evento solicitado por nuestros usuarios, asegurando una revisión minuciosa para su aprobación o rechazo.</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="/img/servicios.png" class="card-img-top" style="max-height: 300px; object-fit: cover;" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><a class="mt-2 py-2 px-4 btn btn-outline-primary fs-4" asp-controller="Services" asp-action="Index">Gestionar Servicios</a></h5>
                        <p class="mt-4 card-text">Gestionar nuestros servicios: agregando, modificando y deshabilitándolos.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Frontend.Web.App.Admin/Views/Parties/Index.cshtml
@model IEnumerable<Backend.Services.DB.Entities.Party>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Eventos</h1>
<hr />

<table class="my-5 table table-striped table-hover">
    <thead>
        <tr class="text-center">
            @*<th>
            @Html.DisplayNameFor(model => model.IDParty)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.IDUser)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.IDPeople)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
            @Html.DisplayFor(modelItem => item.IDParty)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.IDUser)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.IDPeople)
            </td>
            <td class="text-center">
            @Html.DisplayFor(modelItem => item.Active)
            </td>*@
                <td class="text-center">
                    @*@Html.DisplayFor(modelItem => item.Type)*@
                    @if (item.Type == "H")
                    {
                        <span>Soltero</span>
                    }
                    @if (item.Type == "M")
                    {
                        <span>Soltera</span>
                    }
                </td>
                <td class="text-center">
                    @*@Html.DisplayFor(modelItem => item.Estate)*@
                    @if (item.State == "P")
                    {
                        <span class="fw-bold text-warning">Pendiente</span>
                    }
                    @if (item.State == "A")
                    {
                        <span class="fw-bold text-success">Aprobado</span>
                    }
                    @if (item.State == "R")
                    {
                        <span class="fw-bold text-danger">Rechazado</span>
                    }
                </td>
                <td class="fw-bold text-center">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="fw-bold text-center">
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td class="ps-4 text-center">
                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                    <a asp-action="Earring" asp-route-id="@item.IDParty">
                        <i class="me-4 bi bi-pause-circle-fill" style="font-size: 1.5rem; color: orange;"></i>
                    </a>
                    <a asp-action="Approve" asp-route-id="@item.IDParty">
                        <i class="me-4 bi bi-check-circle-fill" style="font-size: 1.5rem; color: green;"></i>
                    </a>
                    <a asp-action="Decline" asp-route-id="@item.IDParty">
                        <i class="bi bi-x-circle-fill" style="font-size: 1.5rem; color: red;"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Frontend.Web.App.Admin/Views/Services/Create.cshtml
@model Backend.Services.DB.Entities.Service

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Servicios</h1>
<h4 class="mt-2">
    <p class="text-secondary">
        <i class="me-2 bi bi-plus-circle-fill" style="font-size: 1.5rem; color: green;"></i>
        Nuevo
    </p>
</h4>
<hr />

<div class="my-5">
    <div class="col-md-5">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="IDService" class="control-label"></label>
                <input asp-for="IDService" class="form-control" />
                <span asp-validation-for="IDService" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>*@
            <div class="form-group">
                <label asp-for="Type" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="mt-4 form-group">
                <label asp-for="Name" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mt-4 form-group">
                <label asp-for="Description" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mt-4 form-group">
                <label asp-for="Price" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="mt-5 form-group">
                <input type="submit" value="Guardar" class="px-4 btn btn-primary fs-5" />
                <a class="ms-2 px-4 btn btn-outline-secondary fs-5" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@*<div>
    <a class="btn btn-outline-secondary" asp-action="Index">Cancelar</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frontend.Web.App.Admin/Views/Services/Delete.cshtml
@model Backend.Services.DB.Entities.Service

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Servicios</h1>
<h4 class="mt-2">
    <p class="text-danger">
        <i class="bi bi-trash3-fill" style="font-size: 1.5rem; color: red;"></i>
        ¿Estás seguro/a de que quieres desactivar este servicio?
    </p>
</h4>
<hr />

<div class="my-5">
    <dl class="row">
        @*<dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.IDService)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.IDService)
        </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>

    <form class="mt-5" asp-action="Delete" asp-route-id="@Model.IDService">
        <input type="submit" value="Desactivar" class="px-4 btn btn-danger fs-5" />
        <a class="ms-2 px-4 btn btn-outline-secondary fs-5" asp-action="Index">Cancelar</a>
    </form>
</div>

Frontend.Web.App.Admin/Views/Services/Details.cshtml
@model Backend.Services.DB.Entities.Service

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Servicios</h1>
<h4 class="mt-2">
    <p class="text-secondary">
        <i class="me-2 bi bi-plus-circle-fill" style="font-size: 1.5rem; color: green;"></i>
        Detalles
    </p>
</h4>
<hr />

<div class="my-5">
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IDService)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IDService)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IDService }) |
    <a asp-action="Index">Volver a la lista</a>
</div>

Frontend.Web.App.Admin/Views/Services/Edit.cshtml
@model Backend.Services.DB.Entities.Service

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Servicios</h1>
<h4 class="mt-2">
    <p class="text-secondary">
        <i class="me-2 bi bi-pencil-fill" style="font-size: 1.5rem; color: orange;"></i>
        Editar
    </p>
</h4>
<hr />

<div class="my-5">
    <div class="col-md-5">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="IDService" class="control-label"></label>*@
                <input asp-for="IDService" class="form-control" type="hidden"/>
                <span asp-validation-for="IDService" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="fw-bold form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="mt-4 form-group">
                <label asp-for="Type" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="mt-4 form-group">
                <label asp-for="Name" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mt-4 form-group">
                <label asp-for="Description" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mt-4 form-group">
                <label asp-for="Price" class="mb-2 fw-bold control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="mt-5 form-group">
                <input type="submit" value="Guardar" class="px-4 btn btn-primary fs-5" />
                <a class="ms-2 px-4 btn btn-outline-secondary fs-5" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frontend.Web.App.Admin/Views/Services/Index.cshtml
@model IEnumerable<Backend.Services.DB.Entities.Service>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Servicios</h1>
<h4 class="mt-2">
    <a asp-action="Create">
        <i class="me-2 bi bi-plus-circle-fill" style="font-size: 1.5rem; color: green;"></i>
        Nuevo
    </a>
</h4>
<hr />

<table class="my-5 table table-striped table-hover">
    <thead>
        <tr class="text-center">
            @*<th>
            @Html.DisplayNameFor(model => model.IDService)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                @Html.DisplayFor(modelItem => item.IDService)
                </td>*@
                <td class ="text-center">
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td class="text-center">
                    @*@Html.DisplayFor(modelItem => item.Type)*@
                    @if (item.Type == "H")
                    {
                        <span>Soltero</span>
                    }
                    @if (item.Type == "M")
                    {
                        <span>Soltera</span>
                    }
                </td class="text-center">
                <td class="fw-bold">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td class="text-end">
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td class="ps-4 text-center">
                    @*@Html.ActionLink("Detalles", "Details", new { id = item.IDService }) |
                    @Html.ActionLink("Editar", "Edit", new { id = item.IDService }) |
                    @Html.ActionLink("Desactivar", "Delete", new { id = item.IDService })*@
                    <a asp-action="Edit" asp-route-id="@item.IDService">
                        <i class="me-4 bi bi-pencil-fill" style="font-size: 1.5rem; color: orange;"></i>
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.IDService">
                        <i class="bi bi-trash3-fill" style="font-size: 1.5rem; color: red;"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Frontend.Web.App.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Goodbyes Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Frontend.Web.App.Admin.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 py-4" style="background-color: #f0f0f0;">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Goodbyes Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parties" asp-action="Index">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Servicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" style="padding: 2rem 0 4rem 0;">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="py-2 container">
            &copy; 2024 - Goodbyes Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>